# Relay API URL (must end with /)
API_BASE_URL=https://api.verifyblind.com/api/Verify/

# EC2 icin false, local Docker icin true
# true ise sabit http://192.168.1.113:5102/api/Verify/ kullanilir
USE_LOCAL_API=true

# Store URL
STORE_URL=https://play.google.com/store/apps/details?id=com.verifyblind.mobile

# Certificate Pinning SHA256 hashes
CERT_PIN_1=sha256/yEep1teva+qeQce6A5iamrmUBGtK5Qtl448H9A/05YA=
CERT_PIN_2=sha256/C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=

# Developer Authorization Public Key (RSA CSP Blob, Base64)
# PCR0 imzalarını doğrulamak için kullanılır. deploy.bat tarafından otomatik güncellenir.
DEVELOPER_PUBLIC_KEY=BgIAAACkAABSU0ExAAgAAAEAAQCpWeZbI7MTzJW3zYeOkgK0c+l7/YtabDxpvfzLKjQrxAwpGjpj5Ui02j2Dnoh4iAgWGRMpPlh6daubXNHAp/m94AG/6ZUuu4Kfb9pA/fiyCwcXUN2DUMIHtYVeHiRMN8SpzTrrVrawBwUDp6SRk3RCaKERV3Q0bisXkDmH5onYUCx6Qx2QKCBEGpqLYDjf0KqwHj+sezItIXvh4Zt/DtXsMxDHrX5reVe+F5WaLDFlhIKvGa6a4cvzsd3yen9zv5eNwmO9S/ay3t5zHN44om9qUsrakUYiVsbohmvI1VFLU2xzKl6LJbhsJvp4as/YXNJ2OCkJCzWPlaxo28Qk7nDC
